### ISSUE TITLE
Very high CPU and RAM consumption

### ISSUE THREAD

**Issue by 0x221e** [matanui159/ReplaySorcery#7] opened 2020-07-26 05:08 UTC
Thanks for your effort to provide Shadowplay alternative on Linux, much appreciated.
I am observing very high CPU & RAM consumption on my Arch setup, below are my specifications and attached useful logs and screenshot :

> CPU : Intel i3-6100
> RAM : 16 GB DDR4 2133 MHz
> GPU: GTX 1050 Ti 4GB

I have been testing with compressQuality = 100 @ 1920x1080p with 60 framerates.

![Screenshot from 2020-07-26 10-26-21](https://user-images.githubusercontent.com/10757422/88471910-de662180-cf2b-11ea-943c-5f8304478bc3.png)
[pmap.log](https://github.com/matanui159/ReplaySorcery/files/4977145/pmap.log)

**Comment by matanui159** [comment] 2020-07-26 05:48
The issue is probably the 60 FPS on an i3 6-th gen. Setting `compressQuality` to 100 is also very memory intensive and not completely neccesary since it goes through x264 compression later anyway (`compressQuality` might also effect performance but I haven't noticed any different on my system). Try using the defaults and see how it handles on your system.

**Comment by 0x221e** [comment] 2020-07-26 05:50
I'll try with different settings and update the result, thanks for the input.

**Comment by matanui159** [comment] 2020-07-28 03:46
I will close this for now, feel free to reopen it if you're still having issues.

**Comment by kattjevfel** [comment] 2020-07-28 19:17
![2020-07-28_20-17-06](https://user-images.githubusercontent.com/6226312/88710796-72481100-d117-11ea-8e82-5a1bde1a7a73.png)
I think I ran into this issue too, 18.7% RAM usage out of 16GB is 1.08GB, or is that with swap included as well? Also 64.9% CPU with a AMD Ryzen 3700X should really not happen.

```
cat .config/replay-sorcery.conf 
offsetX = 2560
offsetY = 0
width = 2560
height = 1440
framerate = 60
duration = 30
compressQuality = 70
outputFile = ~/Videos/ReplaySorcery/%F_%H-%M-%S.mp4
```

**Comment by matanui159** [comment] 2020-07-29 01:44
I do not know why this is happening. The same settings for my computer (Ryzen 1500X) I get only ~7-10% CPU usage.

**Comment by kattjevfel** [comment] 2020-07-29 12:36
@matanui159 How long are you leaving it running? I think this was after an hour or so. Basically I left it running and then I noticed I was running out of RAM while gaming, quickly took that screenshot and killed the service.

**Comment by matanui159** [comment] 2020-07-29 12:41
Sometimes multiple days at a time, no issue

**Comment by kattjevfel** [comment] 2020-07-29 13:38
Started the service and left a movie running so there'd be something constantly changing for it to capture. and after about 22 minutes it was up to 1.5GiB RAM usage (in the video it shows 1.4GiB but it flipped over just afterwards.)

https://giant.gfycat.com/WateryIdleBear.mp4 (x10 speedup)

**Comment by matanui159** [comment] 2020-07-29 13:52
Just came up with a theory and realised I don't free the old buffer when shrinking in `buffer.c`. I need to go to bed now but will be the first thing I do tomorrow after work.

**Closed** 2020-07-30 08:14 UTC

**Comment by kattjevfel** [comment] 2020-08-01 01:10
Still using ~1.5G RAM for me, but perhaps that is simply to be expected? Seems a bit much for 1800 (60*30) jpegs....

**Comment by guglovich** [comment] 2020-12-25 13:11
![изображение](https://user-images.githubusercontent.com/54148165/103135764-a9711d00-46cb-11eb-9ab0-dcbfb55e0124.png)
I have 20%, but that's half the problem. PulseAudio also wants 20%, and that's where it gets interesting.
